puts "🌱 Seeding spices..."


puts "creating activities"
a1= Activity.create(location: "Dahlonega, Georgia", title: "Consolidated Gold Mine", description: "Travel 200 feet underground and 100 years into the past as you explore what was once the largest gold mining operation east of the Mississippi River.")
a2= Activity.create(location: "Dahlonega, Georgia", title: "Crisson Gold Mine", description: "Yearning to awaken your inner prospector? At Crisson Gold Mine, you can purchase ore to take home with you, you can pan for gold, and you can even use a trommel to hunt for gold! This 1847 historic mine is perfect for those hankering for an authentic gold rush experience.")
a3= Activity.create(location: "Dahlonega, Georgia", title: "Georgia Mountain Flaconry", description: "Birds of prey! Hunting! More birds! Oh my! At Georgia Mountain Falconry, visitors can learn about falcons and raptors from Master Class Falconer, Buster Brown, and even hunt with the majestic, winged predators.")
a4= Activity.create(location:"Dahlonega, Georgia", title: "Cavendar Creek Vineyards and Winery", description: "Cavendar Creek Vineyards is a small farm winery that sits at the foothills of the ancient Appalachian Mountains. Looking for a bit of tipple with a lot of Southern hospitality? Search no further.")
a5= Activity.create(location: "Dahlonega, Georgia", title: "Dicks Creek Falls", description: "Easily one of the most beautiful waterfalls in Georgia, framed by towering hardwoods, and spilling over a 60-foot bluff into the Chattooga River below, Dicks Creek Falls and the shoals above it are an escape into the wonderment of the natural landscape of the South.")
a6= Activity.create(location: "Taos, New Mexico", title: "Taos Pueblo", description: "Taos Pueblo is the only living Native American community designated as both a World Heritage Site and a National Historic Landmark. The multi-storied adobe buildings have been continuously inhabited for over 1,000 years.")
a7= Activity.create(location: "Taos, New Mexico", title: "Rio Grande Gorge Bridge", description: "The “Bridge to Nowhere” sits a staggering 650 feet above the Rio Grande, making it the second highest bridge on the U.S. Highway System and the fifth highest bridge in America.")
a8= Activity.create(location: "Taos, New Mexico", title: "Millicent Rogers Museum", description: "Come face to face with more than a thousand years of Southwestern arts and cultures in the fourteen galleries of the Millicent Rogers Museum. Here you will see a wide range of objects including Native American jewelry, pottery, weavings, baskets as well as Hispanic folk art, blankets and so much more.")
# a9= Activity.create(location: "Clinton, New Jersey", title: "Kilhaney's Pickles", description: ,)
# a10= Activity.create(location: "Clinton, New Jersey", title: "Karen's Dollhouse Shop", description: ,)
# a11= Activity.create(location: "Sitka, Alaska", title: "Fortress of the Bear", description: ,)
# a12= Activity.create(location: "Sitka, Alaska", title: "Kayak Sitka Sound", description: ,)
# a13= Activity.create(location: "Sitka, Alaska", title: "Russian Bishops House", description: ,)
# a14= Activity.create(location: "Whitefish, Montana", title: "Glacier National Park", description: ,)
# a15= Activity.create(location: "Whitefish, Montana", title: "Whitefish Lake State Park", description: ,)
# a16= Activity.create(location: "Whitefish, Montana", title: "Great Northern Railway Depot", description: ,)
# a17= Activity.create(location: "Bisbee, Arizona", title: "Lavender Pit", description: ,)
# a18= Activity.create(location: "Bisbee, Arizona", title: "The Bisbee Séance Room", description: ,)
# a19= Activity.create(location: "Marfa, Texas", title: "Marfa Lights", description: ,)
# a20= Activity.create(location: "Marfa, Texas", title: "Highway 90", description: ,)
# a21= Activity.create(location: "Spearfish, South Dakota", title: "D.C. Booth National Fish Hatchery", description: ,)
# a22= Activity.create(location: "Spearfish, South Dakota", title: "Thoen Stone", description: ,)
# a23= Activity.create(location: "Kennebunkport, Maine", title: "Gooch's Beach", description: ,)
# a24= Activity.create(location: "Kennebunkport, Maine", title: "Seashore Trolley Museum", description: ,)
# a25= Activity.create(location: "Port Townsend, Washington", title: "Abandoned Fort Worden Bunkers", description: ,)
# a26= Activity.create(location: "Port Townsend, Washington", title: "Point Wilson Lighthouse", description: ,)
# a27= Activity.create(location: "Guntersville, Alabama", title: "Lake Guntersville State Park", description: ,)
# a28= Activity.create(location: "Guntersville, Alabama", title: "Town Creek Fish Center", description: ,)



puts "creating reviews"
b1 = Review.create(content: "Incredible bit of history tucked two hundred feet underground!", rating: 4, activity_id: a1.id)
b2 = Review.create(content: "My boyfriend and I managed to sneak off from the tour group. Well, he moreover dragged me away, a hand clasped over my mouth. I thought… is this it? Is this the end for me? I mean, a vacation to small town Georgia already felt like death by boredom, so at least murder would be more exciting, you know? He dragged me to the very back of a tunnel—or was it the back? I can’t be sure as all around me was dark. I was wholly deprived of my senses. In that moment, I felt an expanse of possibility swell within me. I waited for the icy grip of death, the sweet release to save me from this stupid vacation. But then something extraordinary happened: I felt his hot breath upon my neck. “Will you marry me?” I gasped. I know I said yes, but I remember not. Suddenly, we were naked. We made love right there on the tunnel floor, our moans of pleasure reverberating through the old mine. Then, the screams of parents and children alike as a lamp flickered on. We turned, naked as the day we were born, to look upon the horrified faces of the tour group. We were kicked out and received a lifetime ban, but I will remember this day and this tour as one of the wildest, most enchanting and exhilarating experiences of my life. 15/10 for both the tour and the orgasm.", rating: 4, activity_id: a1.id)
b3 = Review.create(content: "Kinda like spelunking, minus the adventure, plus a lot of very loud, very smelly kids.", rating: 4, activity_id: a1.id)
b4 = Review.create(content: "Big fan of child labor as a vacation activity.", rating: 4, activity_id: a2.id)
b5 = Review.create(content: "If I have to go to another fucking mine in fucking Dahlonega, Georgia, I will fucking fling myself down a fucking mine shaft.", rating: 4, activity_id: a2.id)
b6 = Review.create(content: "A cool mine, as far as mines go.", rating: 4, activity_id: a2.id)
b7 = Review.create(content: "FUCKIN FALCONS FUCKIN ROCK!!!!!!", rating: 4, activity_id: a3.id)
b8 = Review.create(content: "I now want to be a Falconer. I wish to live my life with the birds. Only birds. I have begun gluing feathers to my arms. I believe I can fly after acutely studying these birds of prey and will be testing my theory from the roof of my house later today.", rating: 4, activity_id: a3.id)
b9 = Review.create(content: "Came for the birds, stayed for Buster himself. The way he handles those birds… mmmmmm", rating: 4, activity_id: a3.id)
b10 = Review.create(content: "Kirkland brand Napa. It is FINE.", rating: 4, activity_id: a4.id)
b11 = Review.create(content: "If you squint your eyes a bit and turn your head to the side, you are still poignantly aware that you are drinking second-rate wine in the foothills of mountains that primarily contain kissing cousins and an opioid crisis.", rating: 4, activity_id: a4.id)
b12 = Review.create(content: "At least I got to get drunk", rating: 4, activity_id: a4.id)
b13 = Review.create(content: "Great swimming. Only a few leeches", rating: 4, activity_id: a5.id)
b14= Review.create(content: "My favorite sight along the Chattooga!", rating: 4, activity_id: a5.id)
b15 = Review.create(content: "So glorious you almost forget you are in the South", rating: 4, activity_id: a5.id)
b16= Review.create(content: "Experience cultural enlightenment at Taos Pueblo. This is an experience you will not want to miss", rating: 4, activity_id: a6.id)
b17 = Review.create(content: "Easy to see why New Mexico is such an inspiring, spiritual place. The people of Taos Pueblo are the beating heart of this small town", rating: 4, activity_id: a6.id)
b18 = Review.create(content: "A magical experience", rating: 4, activity_id: a6.id)
b19 = Review.create(content: "Love a good bridge. This is a good bridge", rating: 4, activity_id: a7.id)
b20 = Review.create(content: "Bridge to nowhere? More like bridge DIRECTLY INTO MY HEART MY GOD IT IS BEAUTIFUL!", rating: 4, activity_id: a7.id)
b21 = Review.create(content: "I proposed to my late wife on this bridge. I promised her I would scatter her ashes over it. Unfortunately, the wind was very strong the day I went, and the ashes blew into my mouth. I had no choice but to swallow. You would think that would be weird or gross, but in my mind, there we were again: kissing after the moment she said yes, just a little… dustier. Beautiful bridge. Highly recommend.", rating: 4, activity_id: a7.id)
b22 = Review.create(content: "There is a lot of stuff here. I like stuff. Lots to look at.", rating: 4, activity_id: a8.id)
b23 = Review.create(content: "Went here on mushrooms and a piece of ancient pottery told me the meaning of life. I cannot remember it now, but I feel it in my soul.", rating: 4, activity_id: a8.id)


puts "✅ Done seeding!"
